### ISSUE TITLE
Creating Debian Package

### ISSUE THREAD

**Issue by gamgee** [babelouest/yder#18]
Hi,

I'm trying to create a yder Debian Package on my Dev Machine (x86) for an ARM based SBC (cross compiling).

The cmake module FindOrcania.cmake automatically downloads orcania and the libyder package is created without any issues.
However, the orcania files are also getting included in the libyder debian package.

install_manifest.txt

/usr/lib/pkgconfig/libyder.pc
/usr/lib/libyder.so.1.4.11
/usr/lib/libyder.so.1.4
/usr/lib/libyder.so
/usr/include/yder.h
/usr/include/yder-cfg.h
/usr/share/doc/yder/examples//Makefile
/usr/share/doc/yder/examples//log_file.c
/usr/share/doc/yder/examples//log_combined.c
/usr/share/doc/yder/examples//log_syslog.c
/usr/share/doc/yder/examples//log_journald.c
/usr/share/doc/yder/examples//log_callback.c
/usr/share/doc/yder/examples//log_console.c
/usr/share/doc/yder/README.md
/usr/lib/pkgconfig/liborcania.pc
/usr/lib/liborcania.so.2.1.1
/usr/lib/liborcania.so.2.1
/usr/lib/liborcania.so
/usr/include/orcania.h
/usr/include/orcania-cfg.h

When I'm installing the package on my target system, I get an error since orcania-cfg.h etc are already installed by the liborcania package.

Is there a way to exclude the orcania files from the yder package? I have the same problem with the ulfius lib.

**Comment by babelouest** [comment]
Hello,

The cmake debian package builder isn't as reliable as a real debian package builder. You can add the cmake flag `-DDOWNLOAD_DEPENDENCIES=OFF` but in your case that might make the build fail.

To help me building all the package with each releases, I've made the package manager [huddersfield](https://github.com/babelouest/huddersfield) that may help you.

With this project, you can build packages of my projects for different distributions, but it doesn't support cross-compiling. (if you want to provide a PR to add this feature, I'll be happy too!)

You can either build a package for a supported distribution using docker:

```shell
user@host:~/huddersfield$ make yder-debian-stable
```

Or build a package for the host, but the whole stack will be installed in the host

```shell
user@host:~/huddersfield$ make yder-local-deb
```

If you have an ARM based SBC machine available with the compile stack, you may be able to build packages for all the projects: orcania, yder, ulfius, hoel, rhonabwy, etc.

**Comment by babelouest** [comment]
@gamgee , were you able to cross build your package?

**Comment by gamgee** [comment]
Hi, thanks for the reply.

I was able to cross compile it by doing the following:
1. Create liborcania Debian package using cmake/cpack
2. Install liborcania on the build system (you can install arm packages on a debian x64 system)
3. Create libyder debian package using cmake/cpack (since I installed liborcania in the previous step, the orcania files don't get included in the yder package)
4. Install libyder on the build system
5. Create ulfius package using cpack/cpack

It's not the best solution but it works for now. I'm going to try to find a cleaner solution as soon as I got time.

I haven't got time to look into huddersfield yet but i will check it out.

**Comment by babelouest** [comment]
It's not ideal but in terms of cross compiling it seems good.
If you manage to do something with Huddersfield, maybe you can be able to build Debian packages more easily.

I'll close this bug then. Feel free to open new ones of you have other issues or more feedbacks.

**Comment by ttngocson** [comment]
I also get an error when cross compile for armhf
this is my CmakeLists.txt:
...
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(tools /usr)
set(CMAKE_C_COMPILER ${tools}/bin/arm-linux-gnueabihf-gcc-8)
set(CMAKE_CXX_COMPILER ${tools}/bin/arm-linux-gnueabihf-g++-8)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
...

and here is the cmake command:
cmake -DDOWNLOAD_DEPENDENCIES=OFF -DWITH_JOURNALD=OFF ..

no error while compiling

but when I call:
y_log_message(Y_LOG_LEVEL_INFO, "Initializing application")
I get "undefined reference to `y_log_message'"
I also do the same for orcania but orcaina succeeds and yder doesn't
where did I go wrong? can you suggest me?

**Comment by babelouest** [comment]
Hello @ttngocson ,

I suggest to open a new issue where you can explain more what you try to achieve and where you have an issue, because your message is not very helpful to understand your problem, in addition to being in the wrong place...
