### ISSUE TITLE
Doxygen docs

### ISSUE THREAD

**Issue by silvioprog** [babelouest/yder#6]
Hello dudes!

What do you thing about adopting some documentation tool like [Doxygen](http://www.stack.nl/~dimitri/doxygen)? :-)

Some advantages:

* generate the HTML reference to be hosted in Github pages (eg: [benmcollins.github.io/libjwt](http://benmcollins.github.io/libjwt/));
* generating the library reference in PDF format (with diagrams using Doxygen's [Graphviz](https://www.graphviz.org) support, eg: [benmcollins.github.io/libjwt/jwt_8h.html](http://benmcollins.github.io/libjwt/jwt_8h.html));
* generating the `man` docs;

So, instead of:

```c
/**
 * Log a message using current parameters
 */
Y_EXTERN void y_log_message(unsigned long type, const char * message, ...);
```
we could do:

```c
/**
 * Log a message using current parameters.
 * @param type Message relevance type.
 * @param message Message string.
 */
Y_EXTERN void y_log_message(unsigned long type, const char * message, ...);
```

**Comment by babelouest** [comment]
Yder now have [doxygen-based documentation](https://babelouest.github.io/yder/doc/html/)!
